baseURL = "http://xoe-labs.github.io/dockery-odoo/"
title = "Dockery-Odoo"
languageCode = "en-us"
theme = "elate"



[params]

  # custom_css = ["css/custom1.css", "css/custom2.css"]

  # Navigation
  [params.navigation]
    brand = "Dockery-Odoo"
    status = "beta"
    work = "<i class='icon-camera'></i>Usage Scenarios"

  # Hero section
  [params.hero]
    title = "![Dockery-Odoo](images/Dockery-Odoo-mixed.svg)"
    subtitle = '''
Empower your <a href="https://odoo.com/" target="_blank">Odoo</a> development workflow with complete, standard & cloud native tooling which is easy to integrate with CI/CD and ready to deploy.

[![GitHub stars](https://img.shields.io/github/stars/xoe-labs/dockery-odoo.svg?longCache=true&style=flat-square&logo=github&label=Stars)](https://github.com/xoe-labs/dockery-odoo)
[![Docker Pulls](https://img.shields.io/docker/pulls/xoelabs/dockery-odoo.svg?longCache=true&style=flat-square)](https://hub.docker.com/r/xoelabs/dockery-odoo/)
[![By XOE](https://img.shields.io/badge/by-XOE Labs-F26524.svg?longCache=true&style=flat-square)](https://xoe.solutions)
'''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Bootstrap your project"
    icon = "icon-wrench"
    description = '''
```shell
$ WORKDIR=$(pwd)/dev/
$ PROJECT=my-project
$ DEFAULT_BRANCH=11.0

$ mkdir -p "${WORKDIR}" && \
  cd "${WORKDIR}" && \
  git clone https://github.com/xoe-labs/dockery-odoo-scaffold.git "${PROJECT}"  && \
  cd  "${PROJECT}" && \
  git submodule add -b "${DEFAULT_BRANCH}" https://github.com/odoo/odoo.git vendor/odoo/cc

# If you have access to enterprise code
$ git submodule add -b "${DEFAULT_BRANCH}" git@github.com:odoo/enterprise.git vendor/odoo/ee
```
'''
    # url = "#"
    # button = "Copy"

  [[params.intro.item]]
    title = "Your project environment"
    description = '''
```shell
$ sed -i "s/{{PROJECT}}/${PROJECT}/" ./Dockerfile ./.env && \
  sed -i "s/{{DEFAULT_BRANCH}}/${DEFAULT_BRANCH}/" ./Dockerfile ./.env

## Review and customize your Dockerfile
$ nano ./Dockerfile

## Review and customize your .env file
$ nano ./.env
```
'''
    # url = "#"
    # button = "Copy"

  [[params.intro.item]]
    title = "Launch using docker-compose"
    description = '''
```shell
# Make use of the provided scripts
$ chmod -R +x ./scripts

# Build the images
$ ./scripts/run-images.sh --pull

# Initialize db server (first run)
$ docker-compose up odoo


# IMPORTANT: Place at least one module in the src folder.
# Or: Jump over to scaffolding before launching.

# Launch your dev instance, Odoo is served on port 80
$ docker-compose up odoo

# Get the admin password
$ cat .adminpwd
```
'''
    # url = "#"
    # button = "Copy"
    icon = "icon-rocket"
  #  img = "img_10.jpg"

  [[params.intro.item]]
    title = "Scaffold your first module"
    description = '''
```shell
# Apply patches to your workdir
$ ./scripts/run-patches.sh

# Scaffold
$ docker-compose run -u $UID scaffold "My next big module"
```
'''
    # url = "#"
    # button = "Copy"
    icon = "icon-frame"
  #  img = "img_10.jpg"

  [[params.intro.item]]
    title = "Poke arround, test and explore"
    description = '''
```shell
# Run a Odoo shell
$ docker-compose run shell -d <DATABASE>

# Test a module
$ docker-compose run tests -d <DATABASE> -i <MODULE>

# Version 12.0 and above:
# View screenshots taken from the js tests
# Just own the output folder by the "magic" id
$ sudo chown -R 9001 _testlogs

```
'''
    # url = "#"
    # button = "Copy"
    icon = "icon-magnifier"
  #  img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"


  # Usege Scenario Section
  [params.work]
    enable = true
    title = "Usage Scenarios"
    description = '''
There are *two main* usage scenarios.
'''
    footertext = """
**Remember:**\n
* Best use a `git submodule` workflow for your vendored repositories.
* For `sparse-checkout` on submodules, start with [this stackoverflow answer](https\\://stackoverflow.com/a/11778551).

**Next Steps:**\n
- Set up your Deployment Infrastructure.<sup>1</sup>
- Customize your CI/CD pipeline.<sup>2</sup>
- Join our growing [Telegram Community](https://t.me/joinchat/ILnVJw7s3ZvKL3mI7AACsw) to get help from other early birds.
- Submit a blog post of your journey to be chosen and linked as reference implementation of either scenario.

<sup>1</sup> [Odoo-Operator](https://xoe-labs.github.io/odoo-operator) will do canary deployments and operate review apps.<br/>
<sup>2</sup> We recomend [GitLab](https://about.gitlab.com/) as the best available development lifecycle companion.
"""
    [[params.work.row]]
      title = "Client Project"
      subtitle = """
**Characteristics:**\n
* Module dependencies are vendored in `vendor/<ORG>/<REPO>/<MODULE>`<sup>1</sup>.
* `src` is used for custom development.
* It is best practice to version control configuration and meta-data.
* Such `custom_config` module satisfies the min. module condition.

<sup>1</sup> Use `sparse-checkout` to only get the modules you need.
"""

    [[params.work.row]]
      title = "Odoo Dev Team"
      subtitle = """
**Characteristics:**\n
* Stable repos are vendored in `vendor/<MYORG>/<REPO>`.
* Module dependencies, if any, same as for Client Projects.
* `src` is used for pre-release module development.
* `src` is a shared workdir on the team's remote repo.
* The team uses feature branches to develop new modules.
* After beta acceptance, the module is moved to it's vendored repo <sup>1</sup>.
* Further maintenance is done on that target repo.

<sup>1</sup> Use "Initial commit" to squash development history **or** `git subtree` commands to preserve it **or**, to get fancy, adopt a `git subrepo` workflow to keep disconnected histories in sync during beta phase.
"""

  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "Dockery-Odoo is the **fastest** and **cleanest** way to get up to speed with your Odoo development."

    [[params.services.item]]
      title = "Docker Based"
      description = "Leverage industry best practices through a docker centric development workflow."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Kubernetes Ready"
      description = "Built with industry standard kubernetes deployment and operation model in mind."
      icon = "icon-cloud-upload"

    [[params.services.item]]
      title = "Convenience by Default"
      description = "Never again waste time on project setup, ever."
      icon = "icon-speedometer"

    [[params.services.item]]
      title = "Ecosystem Player"
      description = "Optimized for excellent teamplay with CI/CD."
      icon = "icon-play"

    [[params.services.item]]
      title = "Descriptive Migration"
      description = "An improved descriptive migration controller build into it."
      icon = "icon-refresh"

    [[params.services.item]]
      title = "Translation (to come)"
      description = "Integration with Transifex, Weblate, GitHub and GitLab."
      icon = "icon-speech"

  # About section
  [params.about]
    enable = true
    title = "Other projects"
    description = "We are commited to excellence in community-driven development at XOE.<br /> Here is a list of some of our most useful tools"

    [[params.about.item]]
      name = "Odoo Operator"
      position = "Deploy Odoo instances reliably at scale with k8s"
      description = ""
      img = "Odoo-Operator-color.svg"
      alt = "Odoo Operator"
      social = [
        ["icon-globe", "https://xoe-labs.github.io/odoo-operator"],
        ["icon-github", "https://github.com/xoe-labs/odoo-operator"]
      ]

    [[params.about.item]]
      name = "Dockery-Odoo Scaffold"
      position = "Bootstrap your project with useful template files."
      description = ""
      img = "Dockery-Odoo-Scaffold-color.svg"
      alt = "Dockery-Odoo Scaffold"
      social = [
        ["icon-github", "https://github.com/xoe-labs/dockery-odoo-scaffold"]
      ]