# CI for o9 repo.
image: docker
stages: [Build]
before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
Image-Deployment:
  stage: Build
  only: [master]
  tags:
    - image-cache
    - docker-socket
  script:
    - docker build -t $CI_REGISTRY_IMAGE:base -f 00-base.Dockerfile --label xoe.docker-odoo-base.commit=$CI_BUILD_REF .
    - docker build -t $CI_REGISTRY_IMAGE:latest -f 11-prod.Dockerfile .
    - docker build -t $CI_REGISTRY_IMAGE:devel -f 12-devel.Dockerfile .
    - docker build -t $CI_REGISTRY_IMAGE:runner -f 13-runner.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:base
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:devel
    - docker push $CI_REGISTRY_IMAGE:runner
