version: '3.4'
services:

  base:
    build:
      context: base
      labels: 
        org.label-schema.vcs-ref: "${CI_BUILD_REF:-devmachine}"
    image: "${CI_REGISTRY_IMAGE:-odoo/base}:latest"

  runner:
    build:
      context: runner
      args:
        FROM_IMAGE: $"{CI_REGISTRY_IMAGE:-odoo/base}"
      labels: 
        com.github.xoes.docker-odoo-base.from-image: "${CI_REGISTRY_IMAGE:-odoo/base}"
    image: "${CI_REGISTRY_IMAGE:-odoo/base}:runner"
    depends_on: ['base']

  migrator:
    build:
      context: migrator
      args:
        FROM_IMAGE: $"{CI_REGISTRY_IMAGE:-odoo/base}"
      labels: 
        com.github.xoes.docker-odoo-base.from-image: "${CI_REGISTRY_IMAGE:-odoo/base}"
    image: "${CI_REGISTRY_IMAGE:-odoo/base}:migrator"
    depends_on: ['base']

  translator:
    build:
      context: translator
      args:
        FROM_IMAGE: $"{CI_REGISTRY_IMAGE:-odoo/base}"
      labels: 
        com.github.xoes.docker-odoo-base.from-image: "${CI_REGISTRY_IMAGE:-odoo/base}"
    image: "${CI_REGISTRY_IMAGE:-odoo/base}:translator"
    depends_on: ['base']