services:
  odoo-base:
    build: 
      context: ./.
      dockerfile: 00-base.Dockerfile
      labels:
        co.devco.repo.docker-odoo-base.commit: $CI_BUILD_REF
    image: $CI_REGISTRY_IMAGE:base
  odoo-cc-deploy:
    depends_on: [odoo-base]
    build: {context: ./. , dockerfile: 10-prod-cc.Dockerfile}
    image: $CI_REGISTRY_IMAGE/cc:latest
  odoo-ee-deploy:
    depends_on: [odoo-base]
    build: {context: ./. , dockerfile: 11-prod-ee.Dockerfile}
    image: $CI_REGISTRY_IMAGE/ee:latest
  odoo-develop:
    depends_on: [odoo-base]
    build: {context: ./. , dockerfile: 12-devel.Dockerfile}
    image: $CI_REGISTRY_IMAGE:devel
  odoo-runner:
    depends_on: [odoo-base]
    build: {context: ./. , dockerfile: 13-runner.Dockerfile}
    image: $CI_REGISTRY_IMAGE:runner
version: '2.1'
